name: Deploy Catalogos to GHCR
on:
  push:
    branches: [ main ]
permissions:
  packages: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        run: |
          # Esto convierte tu usuario ELIZAN626 a elizan626
          REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/$REPO_LOWER/api-catalogos:latest
          docker build -t $IMAGE_ID .
          docker push $IMAGE_ID
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop api-catalogos || true
            docker rm api-catalogos || true
            docker pull ghcr.io/$REPO_LOWER/api-catalogos:latest
            docker run -d --name api-catalogos -p 8000:8000 ghcr.io/$REPO_LOWER/api-catalogos:latest